name: Send APK Reminder Emails

on:
  schedule:
    - cron: '0 13 * * *'  # Every day at 15:00 CEST (13:00 UTC)
  workflow_dispatch:      # Allow manual trigger

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run reminder script
      run: |
        python send_reminders.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

